chore: refactor models
The-Marquis-Gaming/checkers-dojo pull request #36
Opened 2024-12-25 06:32 UTC by RajeshRk18

Closes #35

2024-12-26 09:07 UTC, Gianfranco99 requested changes
Test and build don't work, do sozo build and sozo test, they should all pass green
@RajeshRk18 
![Screenshot 2024-12-26 090517](https://github.com/user-attachments/assets/da4b337b-5640-4d75-8960-bcbb732fe88d)

2024-12-26 09:17 UTC, RajeshRk18 commented
> Test and build don't work, do sozo build and sozo test, they should all pass green
> 
> @RajeshRk18 
> 
> ![Screenshot 2024-12-26 090517](https://github.com/user-attachments/assets/da4b337b-5640-4d75-8960-bcbb732fe88d)

Sure! I will resolve this asap. I didn't get any of these errors

2024-12-28 02:35 UTC, gianalarcon commented
Hi @RajeshRk18. Any updates on this?

2024-12-28 02:52 UTC, RajeshRk18 commented
I will push the changes on Monday.

2024-12-30 16:58 UTC, RajeshRk18 commented
@gianalarcon @Gianfranco99 Tests are passing now!

![image](https://github.com/user-attachments/assets/98ed3df5-5e67-4fbd-8e7b-7fc1ebbd3140)

2024-12-30 17:11 UTC, gianalarcon commented
Hi @RajeshRk18 sorry, we just updated develop branch, pls fix conflicts

2024-12-31 09:04 UTC, RajeshRk18 commented
@gianalarcon Fixed!

2024-12-31 10:02 UTC, 847850277 commented on dojo-starter/src/tests/test_world.cairo
> +            namespace: "checkers_marq", resources: [
please check fmt using `scarb fmt --check`

2024-12-31 10:03 UTC, 847850277 commented on dojo-starter/src/tests/test_world.cairo
>              ContractDefTrait::new(@"checkers_marq", @"actions")
please check fmt using `scarb fmt --check`

2024-12-31 10:37 UTC, gianalarcon commented
workflow for code format should work same as this [PR](https://github.com/The-Marquis-Gaming/checkers-dojo/pull/44)

2024-12-31 13:44 UTC, merged

2024-12-31 14:03 UTC, RajeshRk18 commented
@gianalarcon How will it be paid sir?

2024-12-31 15:01 UTC, gianalarcon commented
Thank you so much for your contribution. I will submit your reward to onlydust platform on few hours