Improve Project Workflows
The-Marquis-Gaming/checkers-dojo pull request #42
Opened 2024-12-27 17:37 UTC by No-bodyq

# Pull Request | Checkers

## 1. Issue Link

- Closes #41 

## 2. Brief Description

Install dojo dynamically from .tools-versions file and add scarb fmt check

## 3. Changes Made

- [ ] it should install the dojo version from .tool-versions.toml file
- [ ] Implent the script to check dojo code format

## 4. Checklist

- [ ] Tests added/updated
- [ ] Documentation updated (if needed)
- [ ] Code follows standards

## 5. Evidence (Optional)

2024-12-27 17:38 UTC, No-bodyq commented
Please review @gianalarcon

2024-12-27 18:29 UTC, No-bodyq commented
Also @gianalarcon , I asked you a question on the discord channel

2024-12-28 02:31 UTC, gianalarcon commented on dojo-starter/.tool-versions
> -dojo 1.0.2
we should not change this file, it is just read only
Can check [here](https://github.com/The-Marquis-Gaming/themarquis-ui/blob/1330d181b11b2332a23034e5c75c6a913c34badd/.github/workflows/contracts.yaml#L41C16-L41C24) how to read it

2024-12-28 02:34 UTC, gianalarcon requested changes
looks good, need to fix the comment I left, also need to attach the github action results you got on your own repo

2024-12-28 04:30 UTC, No-bodyq commented
All done @gianalarcon

2024-12-28 15:58 UTC, merged

2024-12-28 15:59 UTC, gianalarcon commented
Great job! Thanks for your contribution!

2024-12-28 16:11 UTC, No-bodyq commented
Thank you ser